## Function for matrix Operation

Import Numpy

In [26]:
import numpy as np

Matrix Operation Function (Add, Substract, elementwise multiplication, elementwise division)

In [27]:


def matrix_operation(matrix_a, matrix_b, operation):
    # Check if the matrices have the same shape
    if matrix_a.shape != matrix_b.shape:
        raise ValueError("Matrices must have the same dimensions for this operation.")
    
    # Perform the specified operation
    if operation == 'add':
        result = matrix_a + matrix_b
    elif operation == 'subtract':
        result = matrix_a - matrix_b
    elif operation == 'elementwise_multiplication':
        result = matrix_a * matrix_b   
    elif operation == 'elementwise_division':
        result = matrix_a / matrix_b               
    else:
        raise ValueError("Invalid operation. Please choose from 'add', 'subtract', 'elementwise_multiplication', or 'elementwise_division'.")   
    
    return result


Scalar Multiplication, Matrix Multiplication & Division, Matrix Power

In [28]:
#multiplication & division
def scalar_multiply(matrix, scalar):
    return matrix * scalar

def matrix_multiply(matrix_a, matrix_b):
    if matrix_a.shape[1] != matrix_b.shape[0]:
        raise ValueError("Matrices must have compatible dimensions for matrix multiplication.")
    return np.dot(matrix_a, matrix_b)

def matris_division(matrix_a, matrix_b):
    return np.linalg.solve(matrix_a, matrix_b)

def matrix_power(matrix, power):
    return np.linalg.matrix_power(matrix, power)

Transpose Matrix

In [29]:
#transpose
def transpose_matrix(matrix):
    return np.transpose(matrix)

Eigenvalues & Eigenvector

In [30]:
#finding eigenvalues and eigenvectors
def eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return { "Eigenvalues" : eigenvalues,
             "Eigenvector" : eigenvectors
    }

Gaussian Elimination

In [31]:
# simplifying matrix using gaussian elimination
def gaussian_elimination(matrix):
    n = len(matrix)
    for i in range(n):
        # Normalize the i-th row
        matrix[i] = matrix[i] / matrix[i][i]
        
        # Eliminate the i-th column below the i-th row
        for j in range(i + 1, n):
            matrix[j] = matrix[j] - matrix[j][i] * matrix[i]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = matrix[i][-1] - np.sum(matrix[i][i + 1:n] * x[i + 1:n])
    
    return x

# Example usage:
matrix_f = np.array([[2, 1, -1, 8],
                     [-3, -1, 2, -11],
                     [-2, 1, 2, -3]], dtype=float)

solution = gaussian_elimination(matrix_f)
print("Solution Set:\n", solution)

Solution Set:
 [ 2.  3. -1.]


Matrix Determinant

In [32]:
#finding determinant
def matrix_determinant(matrix):
    return np.linalg.det(matrix)

matrix_h = np.array([[1, 2],
                     [3, 4]], dtype=float) # 2 x 2 matrix

matrix_i = np.array([[1, 2, 3],
                     [0, 4, 5],
                     [1, 0, 6]], dtype=float) # 3 x 3 matrix

matrix_j = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]], dtype=float) # 4 x 4 matrix

matrix_k = np.array([[1, 2, 3, 0, 5],
                     [0, 1, 4, 2, 0],
                     [3, 0, 1, 1, 2],
                     [4, 5, 0, 3, 1],
                     [0, 2, 1, 0, 4]], dtype=float) # 5 x 5 matrix

# Example usage:
det_h = matrix_determinant(matrix_h)
det_i = matrix_determinant(matrix_i)
det_j = matrix_determinant(matrix_j)
det_k = matrix_determinant(matrix_k)
print("Determinant of matrix_h:\n", det_h)
print("Determinant of matrix_i:\n", det_i)
print("Determinant of matrix_j:\n", det_j)
print("Determinant of matrix_k:\n", det_k)


Determinant of matrix_h:
 -2.0000000000000004
Determinant of matrix_i:
 22.000000000000004
Determinant of matrix_j:
 0.0
Determinant of matrix_k:
 270.0000000000003


Inverse Matrix

In [33]:
#finding inverse
def matrix_inverse(matrix):
    return np.linalg.inv(matrix)

matrix_g = np.array([[4, 2],
                     [3, 1]], dtype=float)

# Example usage:
inverse_matrix_g = matrix_inverse(matrix_g)  # Use the entire matrix_g
print("Inverse of matrix_g:\n", inverse_matrix_g)

Inverse of matrix_g:
 [[-0.5  1. ]
 [ 1.5 -2. ]]


Covariance Matrix

In [34]:
#finding covariance matrix
def covariance_matrix(matrix):
    return np.cov(matrix, rowvar=False)

# Example usage:
matrix_example = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

cov_matrix = covariance_matrix(matrix_example)
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
 [[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


Mean Vector from Matrix

In [35]:
#finding mean vector
def mean_vector(matrix):
    mean_vec = np.mean(matrix, axis=0)
    mean_matrix = np.tile(mean_vec, (matrix.shape[0], 1))
    return mean_matrix

# Example usage:
mean_matrix = mean_vector(matrix_example)
print("Mean Matrix:\n", mean_matrix)

Mean Matrix:
 [[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


Centered Matrix

In [36]:
#centering matrix
def get_centered_matrix(matrix):
    mean_vec = mean_vector(matrix)
    centered_matrix = matrix_operation(matrix, mean_vec, 'subtract')
    return centered_matrix

# Example usage:
centered_matrix_example = get_centered_matrix(matrix_example)
print("Centered Matrix:\n", centered_matrix_example)

Centered Matrix:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


Weight Vector

In [37]:
#finding weight vector
def weight_vector(X, y):
    # Calculate the transpose of X
    X_transpose = np.transpose(X)
    
    # Calculate the dot product of X_transpose and X
    X_transpose_X = np.dot(X_transpose, X)
    
    # Calculate the inverse of X_transpose_X
    X_transpose_X_inv = np.linalg.inv(X_transpose_X)
    
    # Calculate the dot product of X_transpose and y
    X_transpose_y = np.dot(X_transpose, y)
    
    # Calculate the weight vector w
    w = np.dot(X_transpose_X_inv, X_transpose_y)

    return w

# Example usage:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])
y = np.array([[7],
              [15],
              [23]])

print("Weight Vector:\n", weight_vector(X, y))

Weight Vector:
 [[1.]
 [3.]]


## Example Matrix Operation

In [38]:
# Example usage:
matrix_a = np.array([[0, 2, 7], 
                     [-1, 3, -5]])
matrix_b = np.array([[2, 3, 4], 
                     [1, 3, 1]])
matrix_c = np.array([[1, 2], 
                     [5, 6]])

op1 = matrix_operation(matrix_a, matrix_b, 'add')
op2 = matrix_operation(matrix_a, matrix_b, 'subtract')
#op3 = matrix_operation(matrix_a, matrix_c, 'add') #will resulted in error because matix have different shape

print("Addition Result:\n", op1)
print("Subtraction Result:\n", op2)
#print("Addition Result:\n", op3)

Addition Result:
 [[ 2  5 11]
 [ 0  6 -4]]
Subtraction Result:
 [[-2 -1  3]
 [-2  0 -6]]


In [39]:
op4 = scalar_multiply(matrix_a, 3)
print("Scalar Multiplication Result:\n", op4)

Scalar Multiplication Result:
 [[  0   6  21]
 [ -3   9 -15]]


In [40]:
# New matrix to test matrix_multiply function
matrix_e = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Perform matrix multiplication
op6 = matrix_multiply(matrix_a, matrix_e)
print("Matrix Multiplication Result with new matrix_e:\n", op6)

Matrix Multiplication Result with new matrix_e:
 [[ 57  66  75]
 [-24 -27 -30]]


In [41]:
# New matrix to test eigenvalues_eigenvectors function
matrix_d = np.array([[4, -2],
                     [1,  1]])

# Calculate eigenvalues and eigenvectors
op7 = eigenvalues_eigenvectors(matrix_d)
print("Eigenvalues and Eigenvectors of matrix_d:\n", op7)

Eigenvalues and Eigenvectors of matrix_d:
 {'Eigenvalues': array([3., 2.]), 'Eigenvector': array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])}


In [42]:
# calculate matrix power of matrix_e
op8 = matrix_power(matrix_e, 2)
print("Matrix Power Result:\n", op8)

Matrix Power Result:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [43]:
# transpose matrix a
op9 = transpose_matrix(matrix_a)
print("Original Matrix:\n", matrix_a)
print("Transpose Matrix Result:\n", op9)

Original Matrix:
 [[ 0  2  7]
 [-1  3 -5]]
Transpose Matrix Result:
 [[ 0 -1]
 [ 2  3]
 [ 7 -5]]


## Pincipal Component Analysis

In [44]:
#Principal Component Analysis (manually)
matrix_x= np.array([[2, 0],
                    [0, 2],
                    [3, 1]])
                    
mean_x = mean_vector(matrix_x)
centered_x= get_centered_matrix(matrix_x)
centered_x_transpose = transpose_matrix(centered_x)
centered_x_transpose_centered_x = matrix_multiply(centered_x_transpose, centered_x)
covariance_x = covariance_matrix(matrix_x)

print("Original Matrix:\n", matrix_x)
print("Mean Vector:\n", mean_x)
print("Centered Matrix:\n", centered_x)
print("Transpose of Centered Matrix:\n", centered_x_transpose)
print("Matrix Multiplication Result:\n", centered_x_transpose_centered_x)
print("Covariance Matrix:\n", covariance_x)

eigenvalue_x=eigenvalues_eigenvectors(covariance_x)
print("Eigenvalues and Eigenvectors of matrix_x:\n", eigenvalue_x)

Original Matrix:
 [[2 0]
 [0 2]
 [3 1]]
Mean Vector:
 [[1.66666667 1.        ]
 [1.66666667 1.        ]
 [1.66666667 1.        ]]
Centered Matrix:
 [[ 0.33333333 -1.        ]
 [-1.66666667  1.        ]
 [ 1.33333333  0.        ]]
Transpose of Centered Matrix:
 [[ 0.33333333 -1.66666667  1.33333333]
 [-1.          1.          0.        ]]
Matrix Multiplication Result:
 [[ 4.66666667 -2.        ]
 [-2.          2.        ]]
Covariance Matrix:
 [[ 2.33333333 -1.        ]
 [-1.          1.        ]]
Eigenvalues and Eigenvectors of matrix_x:
 {'Eigenvalues': array([2.86851709, 0.46481624]), 'Eigenvector': array([[ 0.8816746 ,  0.47185793],
       [-0.47185793,  0.8816746 ]])}


In [45]:
#PCA function
def pca(X):
    # Step 1: Calculate the mean vector
    mean_vec = np.mean(X, axis=0)
    
    # Step 2: Center the matrix X by subtracting the mean vector
    X_centered = X - mean_vec
    
    # Step 3: Calculate the covariance matrix of the centered matrix
    covariance_matrix = np.cov(X_centered, rowvar=False)
    
    # Step 4: Compute the eigenvalues and eigenvectors of the covariance matrix
    eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
    
    # Step 5: Transform the original matrix X using the eigenvectors
    X_transformed = np.dot(X_centered, eigenvectors)
    
    return {
        "mean_vector": mean_vec,
        "X_centered": X_centered,
        "X_centered_transpose": X_centered.T,
        "X_centered_X_centered_transpose": np.dot(X_centered.T, X_centered),
        "covariance_matrix": covariance_matrix,
        "eigenvalues": eigenvalues,
        "eigenvectors": eigenvectors,
        "X_transformed": X_transformed
    }

# Example usage:
X = np.array([[2, 0],
              [0, 2],
              [3, 1]])

pca_result = pca(X)
print("Original Matrix:\n", X, "\n")
print("Mean Vector:\n", pca_result["mean_vector"],"\n")
print("Centered Matrix:\n", pca_result["X_centered"])
print("Transpose of Centered Matrix:\n", pca_result["X_centered_transpose"],"\n")
print("Matrix Multiplication Result (X_centered^T * X_centered):\n", pca_result["X_centered_X_centered_transpose"],"\n")
print("Covariance Matrix:\n", pca_result["covariance_matrix"],"\n")
print("Eigenvalues:\n", pca_result["eigenvalues"],"\n")
print("Eigenvectors:\n", pca_result["eigenvectors"],"\n")
print("Transformed Matrix (X_transformed):\n", pca_result["X_transformed"],"\n")

Original Matrix:
 [[2 0]
 [0 2]
 [3 1]] 

Mean Vector:
 [1.66666667 1.        ] 

Centered Matrix:
 [[ 0.33333333 -1.        ]
 [-1.66666667  1.        ]
 [ 1.33333333  0.        ]]
Transpose of Centered Matrix:
 [[ 0.33333333 -1.66666667  1.33333333]
 [-1.          1.          0.        ]] 

Matrix Multiplication Result (X_centered^T * X_centered):
 [[ 4.66666667 -2.        ]
 [-2.          2.        ]] 

Covariance Matrix:
 [[ 2.33333333 -1.        ]
 [-1.          1.        ]] 

Eigenvalues:
 [2.86851709 0.46481624] 

Eigenvectors:
 [[ 0.8816746   0.47185793]
 [-0.47185793  0.8816746 ]] 

Transformed Matrix (X_transformed):
 [[ 0.76574946 -0.72438862]
 [-1.94131559  0.09524472]
 [ 1.17556613  0.6291439 ]] 



## Neural Network


In [50]:
# Python code for doing a forward propagation in a simple neural network
'''
Let say we have a simple neural network with:
    1. Input layer : 2 features
    2. Hidden layer : 2 neurons with ReLU activation function
    3. Output layer : 1 neuron with no activation (linear output)

'''

matrix_n = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # Input layer

w_1 = np.array([[0.1, 0.2],
                [0.3, 0.4]]) # Weights for hidden layer

b_1 = np.array([0.1, 0.2]) # Bias for hidden layer

w_2 = np.array([[0.5],
                [0.6]]) # Weights for output layer

b_2 = np.array([0.3]) # Bias for output layer

def forward_propagation(X, w1, b1, w2, b2):
    # Calculate the dot product of X and w1
    z1 = np.dot(X, w1) + b1
    
    # Apply the ReLU activation function
    a1 = np.maximum(0, z1)
    
    # Calculate the dot product of a1 and w2
    z2 = np.dot(a1, w2) + b2
    
    # The output layer has no activation function
    a2 = z2
    
    return {
        "z1": z1,
        "a1": a1,
        "z2": z2,
        "a2": a2
    }

In [51]:
#test case
forward_propagation_result = forward_propagation(matrix_n, w_1, b_1, w_2, b_2)
print("Forward Propagation Result:\n", forward_propagation_result)

Forward Propagation Result:
 {'z1': array([[0.8, 1.2],
       [1.6, 2.4],
       [2.4, 3.6]]), 'a1': array([[0.8, 1.2],
       [1.6, 2.4],
       [2.4, 3.6]]), 'z2': array([[1.42],
       [2.54],
       [3.66]]), 'a2': array([[1.42],
       [2.54],
       [3.66]])}


In [52]:
# Python code for doing a backward propagation in a simple neural network
# Let's use the same neural network architecture as before

def backward_propagation(X, Y, w1, b1, w2, b2, forward_propagation_result):
    # Get the forward propagation results
    a1 = forward_propagation_result["a1"]
    a2 = forward_propagation_result["a2"]
    
    # Calculate the error in the output layer
    error_output = a2 - Y
    
    # Calculate the gradient of the loss with respect to w2
    grad_w2 = np.dot(a1.T, error_output)
    
    # Calculate the gradient of the loss with respect to b2
    grad_b2 = np.sum(error_output, axis=0)
    
    # Calculate the error in the hidden layer
    error_hidden = np.dot(error_output, w2.T)
    
    # Calculate the gradient of the loss with respect to w1
    grad_w1 = np.dot(X.T, error_hidden * (a1 > 0))
    
    # Calculate the gradient of the loss with respect to b1
    grad_b1 = np.sum(error_hidden * (a1 > 0), axis=0)
    
    return {
        "grad_w1": grad_w1,
        "grad_b1": grad_b1,
        "grad_w2": grad_w2,
        "grad_b2": grad_b2
    }

#test case
Y = np.array([[0.5]]) # True output
backward_propagation_result = backward_propagation(matrix_n, Y, w_1, b_1, w_2, b_2, forward_propagation_result)
print("Backward Propagation Result:\n", backward_propagation_result)

Backward Propagation Result:
 {'grad_w1': array([[11.42 , 13.704],
       [14.48 , 17.376]]), 'grad_b1': array([3.06 , 3.672]), 'grad_w2': array([[11.584],
       [17.376]]), 'grad_b2': array([6.12])}
