In [1]:
import numpy as np
from numpy.linalg import svd

# User-Movie Ratings Matrix (5x5 example with missing values as 0)
R = np.array([
    [5, 3, 0, 1, 0],
    [4, 0, 0, 1, 0],
    [1, 1, 0, 5, 4],
    [0, 0, 5, 4, 0],
    [0, 1, 5, 4, 0]
], dtype=float)

# Step 1: Perform SVD
U, S, VT = svd(R, full_matrices=False)

# Step 2: Reduce Dimensionality
k = 2  # Number of features to keep
U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

# Step 3: Reconstruct the Matrix
R_approx = np.dot(np.dot(U_k, S_k), VT_k)

# Print Results
print("Original Matrix (R):\n", R)
print("\nReduced Singular Values (S_k):\n", S_k)
print("\nReconstructed Matrix (R_approx):\n", np.round(R_approx, 2))

Original Matrix (R):
 [[5. 3. 0. 1. 0.]
 [4. 0. 0. 1. 0.]
 [1. 1. 0. 5. 4.]
 [0. 0. 5. 4. 0.]
 [0. 1. 5. 4. 0.]]

Reduced Singular Values (S_k):
 [[10.13139716  0.        ]
 [ 0.          6.94299702]]

Reconstructed Matrix (R_approx):
 [[ 4.77  1.98 -0.85  1.69  1.12]
 [ 3.14  1.31 -0.51  1.16  0.74]
 [ 2.42  1.34  2.11  3.56  1.12]
 [-0.56  0.33  4.39  4.36  0.81]
 [-0.27  0.46  4.36  4.49  0.88]]
